### ISSUE TITLE
Links do not function

### ISSUE THREAD

**Issue by DeastinY** [r0bin-fr/artigene#1]
Hey there!
Projects seems like a real charmer, but (at least for me) all the links from the readme are dead :/
Fixable?

**Comment by r0bin-fr** [comment]
hello, great to see your interest ! i just tested the links, all of them works for me, only roasthacker.com seems down. i saw his https://github.com/evquink/RoastGenie and 3D files here: https://www.thingiverse.com/thing:1496451 maybe you can also check google images with "roasthacker" keyword. 
let me know if you need anything else, and keep me updated if you start your project ;)

**Comment by Steve9F** [comment]
Great project. I've been researching making similar mods and love the detail and effort you've put into yours. I confess that I've struggled a bit reading through the Google translate version of the French forum posts. Do you have a summary of the hardware you're using and wiring you can post? 

@DeastinY you can find an archive of RoastGenie site here: https://web.archive.org/web/20161024205547/http://roasthacker.com/?page_id=29

**Comment by DeastinY** [comment]
Alright, nice! Thank you both very much!
